# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-MiniCalendar
version:      0.09
version_from: lib/Tk/MiniCalendar.pm
installdirs:  site
requires:
    Date::Calc:                    5
    Tk:                            0
    Tk::XPMs:                      1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
